checkpoint_dir: PATH_TO_PRETRAINED_CHECKPOINT
test_save_path: PATH_TO_SAVE_TEST_IMAGE
bs: 48
lr: 5e-5
exp_name: debug
output_dir: PATH_TO_SAVE_OUTPUT
num_train_epochs: 8
gradient_accumulation_steps: 1
warmup_steps: 400
save_steps: 1000
logging_steps: 10
dataloader_num_workers: 8
save_total_limit: 30





